apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-promtail
  labels:
    app.kubernetes.io/name: promtail
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  endpoints:
    - port: http-metrics
