---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

namespace: paperless-ngx

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/instance: redis
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: paperless-ngx

images:
  - name: redis
    newName: redis
    newTag: "6.2"
