kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loki-promtail
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
subjects:
  - kind: ServiceAccount
    name: loki-promtail
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: loki-promtail
  apiGroup: rbac.authorization.k8s.io
