apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-root-passwords
spec:
  secretStoreRef:
    name: postgresql
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: postgresql-root-passwords
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque

      data:
        postgresql-password: "{{ .postgresql_password }}"
        password: "{{ .user_password }}"
        replication-password: "{{ .replication_password }}"

  data:
    - secretKey: postgresql_password
      remoteRef:
        key: postgresql/root
        property: postgresql_password
        decodingStrategy: None
    - secretKey: user_password
      remoteRef:
        key: postgresql/root
        property: user_password
        decodingStrategy: None
    - secretKey: replication_password
      remoteRef:
        key: postgresql/root
        property: replication_password
        decodingStrategy: None
