---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

resources:
  - Namespace-databases.yaml
  - ServiceAccount-postgresql.yaml
  - SecretStore-postgresql.yaml
  - ExternalSecret-postgresql-root-passwords.yaml
  - HelmRelease-postgresql.yaml
