apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: postgresql-root-passwords
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          role: "databases-postgresql"
          serviceAccountRef:
            name: postgresql
            namespace: databases
