apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: simon.bordeyne@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - dns01:
        cloudflare:
          apiKeySecretRef:
            name: cloudflare-api-key
            key: CLOUDFLARE_API_KEY
          email: simon.bordeyne@gmail.com
