apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "cert-manager-cloudflare"
spec:
  secretStoreRef:
    name: cert-manager
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: cloudflare-api-key
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque

      data:
        CLOUDFLARE_API_KEY: "{{ .key }}"
        CLOUDFLARE_API_EMAIL: "{{ .email }}"

  data:
    - secretKey: key
      remoteRef:
        key: cloudflare/credentials
        property: api_key
        decodingStrategy: None
    - secretKey: email
      remoteRef:
        key: cloudflare/credentials
        property: email
        decodingStrategy: None
