---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ClusterIssuer-selfsigned.yaml
  - Certificate-selfsigned-ca.yaml
  - ClusterIssuer-ca.yaml
  - SecretStore-cert-manager.yaml
  - ExternalSecret-cert-manager-cloudflare.yaml
  - ClusterIssuer-lets-encrypt.yaml
