apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          role: "cert-manager-cert-manager"
          serviceAccountRef:
            name: cert-manager
            namespace: cert-manager
