apiVersion: v1
kind: Service
metadata:
  name: loki-canary
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki-canary
  ports:
  - name: http-metrics
    protocol: TCP
    port: 3500
    targetPort: 3500
