apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml
  - grafana
  - prometheus
  - alert-manager
  - loki
  - kube-control-plane
  - kube-state-metrics
  - node-exporter
  - promtail
  - prometheus-adapter
  - smart-exporter
  - speedtest-exporter
