apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vault
  namespace: flux-system
spec:
  approvePlan: auto
  interval: 10m
  path: ./terraform/workspaces/vault
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: vault-credentials
