apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: external-dns
  namespace: flux-system
spec:
  approvePlan: auto
  interval: 1m
  path: ./terraform/workspaces/external-dns
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
