
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whisparr

commonLabels:
  app.kubernetes.io/name: whisparr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: whisparr
  app.kubernetes.io/component: whisparr

resources:
  - ./manifests/namespace.yaml
  - ./manifests/pvc.yaml
  - ./manifests/deployment.yaml
  - ./manifests/service.yaml
  - ./manifests/ingress.yaml

configMapGenerator:
  - name: whisparr-env
    namespace: whisparr
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: whisparr
        app.kubernetes.io/part-of: arrstack
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: whisparr
        app.kubernetes.io/component: whisparr
    literals:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Paris

images:
  - name: whisparr
    newName: ghcr.io/hotio/whisparr
    newTag: latest
