apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smtp-relay
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "patch", "create"]
