---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - daemonset.yaml
  - network-policy.yaml
  - service.yaml
  - prometheus-rule.yaml
  - service-monitor.yaml

commonLabels:
  app.kubernetes.io/component: exporter
  app.kubernetes.io/name: node-exporter
  app.kubernetes.io/version: 1.6.1
