apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pihole-exporter
  labels:
    app.kubernetes.io/component: pihole-exporter
    app.kubernetes.io/instance: pihole-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/part-of: pihole
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  pihole-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  pihole-exporter
    spec:
      containers:
      - image:   ekofr/pihole-exporter:latest
        name:  pihole-exporter
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "50m"
            memory: "100M"
        env:
        - name:  PIHOLE_PROTOCOL
          value:  http
        - name:  PIHOLE_HOSTNAME
          value:  pihole.pihole.svc.cluster.local
        - name: PIHOLE_PORT
          value:  "80"
        - name: PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: WEBPASSWORD
              name: password
              optional: false
        - name: PORT
          value: "9617"
        ports:
        - containerPort:  9617
          name:  metrics
