
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - StatefulSet-jellyfin.yaml
  - Service-jellyfin.yaml
  - Ingress-jellyfin.yaml

images:
  - name: jellyfin
    newName: jellyfin/jellyfin
    newTag: "10.10.7"
