apiVersion: monitoring.coreos.com/v1
kind: VMServiceScrape
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 25s
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
    - action: replace
      sourceLabels: [__name__]
      targetLabel: job
      regex: (.*)
      replacement: jellyfin_${1}
  namespaceSelector:
    matchNames:
    - jellyfin
