apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: komga

resources:
- pvc.yaml
- service.yaml
- deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: komga
  app.kubernetes.io/component: komga
  app.kubernetes.io/version: 1.10.4
  app.kubernetes.io/instance: komga
  app.kubernetes.io/managed-by: kustomize

secretGenerator:
- name: komga-env
  options:
    disableNameSuffixHash: true
  env: config/.env
  type: Opaque

configMapGenerator:
- name: komga-config
  options:
    disableNameSuffixHash: true
  files:
  - config/application.yaml

images:
- name: komga
  newName: gotson/komga
  newTag: 1.23.1
