apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: paperless-redis
  namespace: paperless-ngx
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 500Mi
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: json
