---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - service-account.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - alert-manager.yaml
  - service.yaml
  - service-monitor.yaml

commonLabels:
  app.kubernetes.io/component: alert-router
  app.kubernetes.io/name: alertmanager
