apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smart-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: smart-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/component: smart-exporter
    app.kubernetes.io/instance: smart-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: "294"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smart-exporter
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: smart-exporter
        image: antilax3/smart-exporter:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: smart-exporter-config
            items:
              - key: smartexporter.json
                path: smartexporter.json
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: true
