---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  # - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml

commonLabels:
  app.kubernetes.io/name: kube-state-metrics
