
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgadmin

resources:
  - ./manifests/namespace.yaml

commonLabels:
  app.kubernetes.io/name: pgadmin
  app.kubernetes.io/instance: pgadmin
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: pgadmin
  app.kubernetes.io/version: 7.4
