deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  structuredConfig:
    schema_config:
          configs:
          - from: "2022-01-11"
            index:
              period: 24h
              prefix: loki_index_
            object_store: filesystem
            schema: v12
            store: boltdb-shipper
          - from: "2024-04-13"
            index:
              period: 24h
              prefix: loki_tsdb_index_
            object_store: filesystem
            schema: v13
            store: tsdb

chunksCache:
  replicas: 0
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

singleBinary:
  replicas: 1
  autoscaling:
    enabled: false

  persistence:
    enabled: true
    storageClass: nfs-client
    size: 30Gi

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: true
  servicemonitor:
    enabled: true
  lokiCanary:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
