apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app.kubernetes.io/name: speedtest-exporter
  app.kubernetes.io/managed-by: kustomize

resources:
  - daemonset.yaml
  - service.yaml
  - service-monitor.yaml

images:
  - name: speedtest-exporter
    newName: billimek/prometheus-speedtest-exporter
    newTag: latest
