apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
spec:
  selector:
    app: speedtest-exporter
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: metrics
    protocol: TCP
    port: 9469
    targetPort: 9469
