apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "external-dns-pihole"
spec:
  secretStoreRef:
    name: external-dns
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: external-dns-pihole-password
    creationPolicy: Owner
    deletionPolicy: Delete

    # Specify a blueprint for the resulting Kind=Secret
    template:
      type: Opaque

      # Use inline templates to construct your desired config file that contains your secret
      data:
        PIHOLE_PASSWORD: "{{ .pihole_password }}"

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: pihole_password
      remoteRef:
        key: pihole/credentials
        property: password
        decodingStrategy: None
