
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr

commonLabels:
  app.kubernetes.io/name: bazarr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: bazarr
  app.kubernetes.io/component: bazarr

resources:
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml

configMapGenerator:
  - name: bazarr-env
    namespace: bazarr
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: bazarr
        app.kubernetes.io/part-of: arrstack
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: bazarr
        app.kubernetes.io/component: bazarr
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris

images:
  - name: bazarr
    newName: lscr.io/linuxserver/bazarr
    newTag: latest
