apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cloudflare-ddns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: utils-cloudflare-ddns-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: utils
        app.kubernetes.io/name: cloudflare-ddns
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: utils-cloudflare-ddns-app
    spec:
      serviceAccountName: cloudflare-ddns
      containers:
      - image: timothyjmiller/cloudflare-ddns:latest
        name: cloudflare-ddns
        resources:
          requests:
            cpu: "1m"
            memory: "5M"
          limits:
            cpu: "50m"
            memory: "32Mi"
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Paris"
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
      volumes:
        - name: config
          secret:
            secretName: cloudflare-ddns-config
      restartPolicy: Always
