apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "cloudflare-ddns-config"
spec:
  secretStoreRef:
    name: cloudflare-ddns
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: cloudflare-ddns-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - kind: ConfigMap
          name: cloudflare-ddns-config-template

  data:
    - secretKey: api_key
      remoteRef:
        key: cloudflare/credentials
        property: api_key
        decodingStrategy: None
    - secretKey: api_token
      remoteRef:
        key: cloudflare/credentials
        property: api_token
        decodingStrategy: None
    - secretKey: email
      remoteRef:
        key: cloudflare/credentials
        property: email
        decodingStrategy: None
