apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bazarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: bazarr
      initContainers:
        - name: init-bazarr
          image: busybox
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["sh"]
          args:
            - -c
            - mkdir -p /config/config && rm -f /config/config/config.yaml && cp -f /cfg/config.yaml /config/config/config.yaml && chown -R 1000:1000 /config
          volumeMounts:
            - name: config
              mountPath: /cfg/config.yaml
              subPath: config.yaml
            - name: config-pvc
              mountPath: /config
      containers:
        - image: bazarr
          name: bazarr
          resources:
            limits:
              cpu: "50m"
              memory: "110M"
            requests:
              cpu: "1m"
              memory: "10M"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          ports:
          - containerPort:  6767
            name:  http
          volumeMounts:
          - mountPath: /media
            name: media
          - mountPath: /config
            name: config-pvc

      volumes:
        - name: media
          nfs:
            path: /tank/media
            server: "192.168.1.42"
        - name: config-pvc
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: config
          secret:
            secretName: bazarr-config
