apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "bazarr-config"
spec:
  secretStoreRef:
    name: bazarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: bazarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: bazarr-config-template
            items:
              - key: config.yaml

  data:
    - secretKey: bazarr_api_key
      remoteRef:
        key: arr-stack/bazarr
        property: api_key
        decodingStrategy: None
    - secretKey: bazarr_flask_secret_key
      remoteRef:
        key: arr-stack/bazarr
        property: flask_secret_key
        decodingStrategy: None
    - secretKey: bazarr_postgres_password
      remoteRef:
        key: postgresql/bazarr
        property: password
        decodingStrategy: None
    - secretKey: bazarr_postgres_user
      remoteRef:
        key: postgresql/bazarr
        property: username
        decodingStrategy: None
    - secretKey: radarr_api_key
      remoteRef:
        key: arr-stack/radarr
        property: api_key
        decodingStrategy: None
    - secretKey: sonarr_api_key
      remoteRef:
        key: arr-stack/sonarr
        property: api_key
        decodingStrategy: None
    - secretKey: anti_captcha_api_key
      remoteRef:
        key: anti-captcha/credentials
        property: api_key
        decodingStrategy: None
