apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisparr-config
spec:
  secretStoreRef:
    name: whisparr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: whisparr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      data:
        # https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
        WHISPARR__APP__INSTANCENAME: Whisparr
        WHISPARR__APP__LAUNCHBROWSER: "false"
        WHISPARR__AUTH__APIKEY: "{{ .whisparr_api_key }}"
        WHISPARR__AUTH__ENABLED: "true"
        WHISPARR__AUTH__METHOD: "Forms"
        WHISPARR__LOG__LEVEL: info
        WHISPARR__POSTGRES__HOST: postgresql.databases.svc.cluster.local
        WHISPARR__POSTGRES__PORT: "5432"
        WHISPARR__POSTGRES__USER: "{{ .whisparr_postgres_user }}"
        WHISPARR__POSTGRES__PASSWORD: "{{ .whisparr_postgres_password }}"
        WHISPARR__POSTGRES__MAINDB: whisparr
        WHISPARR__POSTGRES__LOGDB: whisparr_log
        WHISPARR__SERVER__BINDADDRESS: "*"
        WHISPARR__SERVER__PORT: "6969"
        WHISPARR__UPDATE__MECHANISM: Docker
        WHISPARR__UPDATE__BRANCH: main

  data:
    - secretKey: whisparr_api_key
      remoteRef:
        key: arr-stack/whisparr
        property: api_key
        decodingStrategy: None
    - secretKey: whisparr_postgres_password
      remoteRef:
        key: postgresql/whisparr
        property: password
        decodingStrategy: None
    - secretKey: whisparr_postgres_user
      remoteRef:
        key: postgresql/whisparr
        property: username
        decodingStrategy: None
