apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-config
spec:
  secretStoreRef:
    name: prowlarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: prowlarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: prowlarr-config-template
            items:
              - key: config.xml

  data:
    - secretKey: prowlarr_api_key
      remoteRef:
        key: arr-stack/prowlarr
        property: api_key
        decodingStrategy: None
    - secretKey: prowlarr_postgres_password
      remoteRef:
        key: postgresql/prowlarr
        property: password
        decodingStrategy: None
    - secretKey: prowlarr_postgres_user
      remoteRef:
        key: postgresql/prowlarr
        property: username
        decodingStrategy: None
