apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-config
spec:
  secretStoreRef:
    name: radarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: radarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: radarr-config-template
            items:
              - key: config.xml

  data:
    - secretKey: radarr_api_key
      remoteRef:
        key: arr-stack/radarr
        property: api_key
        decodingStrategy: None
    - secretKey: radarr_postgres_password
      remoteRef:
        key: postgresql/radarr
        property: password
        decodingStrategy: None
    - secretKey: radarr_postgres_user
      remoteRef:
        key: postgresql/radarr
        property: username
        decodingStrategy: None
