apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-config
spec:
  secretStoreRef:
    name: radarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: radarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      data:
        # https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
        RADARR__APP__INSTANCENAME: Radarr
        RADARR__APP__LAUNCHBROWSER: "false"
        RADARR__AUTH__APIKEY: "{{ .radarr_api_key }}"
        RADARR__AUTH__ENABLED: "true"
        RADARR__AUTH__METHOD: "Forms"
        RADARR__LOG__LEVEL: info
        RADARR__POSTGRES__HOST: postgresql.databases.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: "{{ .radarr_postgres_user }}"
        RADARR__POSTGRES__PASSWORD: "{{ .radarr_postgres_password }}"
        RADARR__POSTGRES__MAINDB: radarr
        RADARR__POSTGRES__LOGDB: radarr_log
        RADARR__SERVER__BINDADDRESS: "*"
        RADARR__SERVER__PORT: "7878"
        RADARR__UPDATE__MECHANISM: Docker
        RADARR__UPDATE__BRANCH: main

  data:
    - secretKey: radarr_api_key
      remoteRef:
        key: arr-stack/radarr
        property: api_key
        decodingStrategy: None
    - secretKey: radarr_postgres_password
      remoteRef:
        key: postgresql/radarr
        property: password
        decodingStrategy: None
    - secretKey: radarr_postgres_user
      remoteRef:
        key: postgresql/radarr
        property: username
        decodingStrategy: None
