apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-config
spec:
  secretStoreRef:
    name: sonarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: sonarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: sonarr-config-template
            items:
              - key: config.xml

  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: arr-stack/sonarr
        property: api_key
        decodingStrategy: None
    - secretKey: sonarr_postgres_password
      remoteRef:
        key: postgresql/sonarr
        property: password
        decodingStrategy: None
    - secretKey: sonarr_postgres_user
      remoteRef:
        key: postgresql/sonarr
        property: username
        decodingStrategy: None
