apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr-config
spec:
  secretStoreRef:
    name: readarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: readarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      data:
        # https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
        READARR__APP__INSTANCENAME: Readarr
        READARR__APP__LAUNCHBROWSER: "false"
        READARR__AUTH__APIKEY: "{{ .readarr_api_key }}"
        READARR__AUTH__ENABLED: "true"
        READARR__AUTH__METHOD: "Forms"
        READARR__LOG__LEVEL: info
        READARR__POSTGRES__HOST: postgresql.databases.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: "{{ .readarr_postgres_user }}"
        READARR__POSTGRES__PASSWORD: "{{ .readarr_postgres_password }}"
        READARR__POSTGRES__MAINDB: readarr
        READARR__POSTGRES__LOGDB: readarr_log
        READARR__SERVER__BINDADDRESS: "*"
        READARR__SERVER__PORT: "8787"
        READARR__UPDATE__MECHANISM: Docker
        READARR__UPDATE__BRANCH: main
  data:
    - secretKey: readarr_api_key
      remoteRef:
        key: arr-stack/readarr
        property: api_key
        decodingStrategy: None
    - secretKey: readarr_postgres_password
      remoteRef:
        key: postgresql/readarr
        property: password
        decodingStrategy: None
    - secretKey: readarr_postgres_user
      remoteRef:
        key: postgresql/readarr
        property: username
        decodingStrategy: None
