apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission-config
spec:
  secretStoreRef:
    name: transmission
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: transmission-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: transmission-config-template
            items:
              - key: settings.json

  data:
    - secretKey: transmission_rpc_username
      remoteRef:
        key: arr-stack/transmission
        property: username
        decodingStrategy: None
    - secretKey: transmission_rpc_password
      remoteRef:
        key: arr-stack/transmission
        property: password
        decodingStrategy: None
