apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-config
spec:
  secretStoreRef:
    name: sonarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: sonarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      data:
        # https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
        SONARR__APP__INSTANCENAME: Sonarr
        SONARR__APP__LAUNCHBROWSER: "false"
        SONARR__AUTH__APIKEY: "{{ .sonarr_api_key }}"
        SONARR__AUTH__ENABLED: "true"
        SONARR__AUTH__METHOD: "Forms"
        SONARR__LOG__LEVEL: info
        SONARR__POSTGRES__HOST: postgresql.databases.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: "{{ .sonarr_postgres_user }}"
        SONARR__POSTGRES__PASSWORD: "{{ .sonarr_postgres_password }}"
        SONARR__POSTGRES__MAINDB: sonarr
        SONARR__POSTGRES__LOGDB: sonarr_log
        SONARR__SERVER__BINDADDRESS: "*"
        SONARR__SERVER__PORT: "8989"
        SONARR__UPDATE__MECHANISM: Docker
        SONARR__UPDATE__BRANCH: main
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: arr-stack/sonarr
        property: api_key
        decodingStrategy: None
    - secretKey: sonarr_postgres_password
      remoteRef:
        key: postgresql/sonarr
        property: password
        decodingStrategy: None
    - secretKey: sonarr_postgres_user
      remoteRef:
        key: postgresql/sonarr
        property: username
        decodingStrategy: None
