apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission-credentials
spec:
  secretStoreRef:
    name: transmission
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: transmission-credentials
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque

      data:
        username: "{{ .transmission_rpc_username }}"
        password: "{{ .transmission_rpc_password }}"

  data:
    - secretKey: transmission_rpc_username
      remoteRef:
        key: arr-stack/transmission
        property: username
        decodingStrategy: None
    - secretKey: transmission_rpc_password
      remoteRef:
        key: arr-stack/transmission
        property: password
        decodingStrategy: None
