apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-config
spec:
  secretStoreRef:
    name: prowlarr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: prowlarr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      data:
        # https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
        PROWLARR__APP__INSTANCENAME: Prowlarr
        PROWLARR__APP__LAUNCHBROWSER: "false"
        PROWLARR__AUTH__APIKEY: "{{ .prowlarr_api_key }}"
        PROWLARR__AUTH__ENABLED: "true"
        PROWLARR__AUTH__METHOD: "Forms"
        PROWLARR__LOG__LEVEL: info
        PROWLARR__POSTGRES__HOST: postgresql.databases.svc.cluster.local
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: "{{ .prowlarr_postgres_user }}"
        PROWLARR__POSTGRES__PASSWORD: "{{ .prowlarr_postgres_password }}"
        PROWLARR__POSTGRES__MAINDB: radarr
        PROWLARR__POSTGRES__LOGDB: radarr_log
        PROWLARR__SERVER__BINDADDRESS: "*"
        PROWLARR__SERVER__PORT: "9696"
        PROWLARR__UPDATE__MECHANISM: Docker
        PROWLARR__UPDATE__BRANCH: main

  data:
    - secretKey: prowlarr_api_key
      remoteRef:
        key: arr-stack/prowlarr
        property: api_key
        decodingStrategy: None
    - secretKey: prowlarr_postgres_password
      remoteRef:
        key: postgresql/prowlarr
        property: password
        decodingStrategy: None
    - secretKey: prowlarr_postgres_user
      remoteRef:
        key: postgresql/prowlarr
        property: username
        decodingStrategy: None
