apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisparr-config
spec:
  secretStoreRef:
    name: whisparr
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: whisparr-config
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque
      templateFrom:
        - configMap:
            name: whisparr-config-template
            items:
              - key: config.xml

  data:
    - secretKey: whisparr_api_key
      remoteRef:
        key: arr-stack/whisparr
        property: api_key
        decodingStrategy: None
    - secretKey: whisparr_postgres_password
      remoteRef:
        key: postgresql/whisparr
        property: password
        decodingStrategy: None
    - secretKey: whisparr_postgres_user
      remoteRef:
        key: postgresql/whisparr
        property: username
        decodingStrategy: None
