
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
  - Namespace-arr-stack.yaml
  - ServiceAccount-bazarr.yaml
  - ServiceAccount-radarr.yaml
  - ServiceAccount-prowlarr.yaml
  - ServiceAccount-readarr.yaml
  - ServiceAccount-sonarr.yaml
  - ServiceAccount-whisparr.yaml
  - ServiceAccount-transmission.yaml
  - SecretStore-bazarr.yaml
  - SecretStore-radarr.yaml
  - SecretStore-prowlarr.yaml
  - SecretStore-readarr.yaml
  - SecretStore-sonarr.yaml
  - SecretStore-whisparr.yaml
  - SecretStore-transmission.yaml
  - ExternalSecret-bazarr-config.yaml
  - ExternalSecret-radarr-config.yaml
  - ExternalSecret-prowlarr-config.yaml
  - ExternalSecret-readarr-config.yaml
  - ExternalSecret-sonarr-config.yaml
  - ExternalSecret-whisparr-config.yaml
  - ExternalSecret-transmission-config.yaml
  - ExternalSecret-transmission-credentials.yaml
  - PersistentVolumeClaim-bazarr-config.yaml
  - PersistentVolumeClaim-radarr-config.yaml
  - PersistentVolumeClaim-prowlarr-config.yaml
  - PersistentVolumeClaim-readarr-config.yaml
  - PersistentVolumeClaim-sonarr-config.yaml
  - PersistentVolumeClaim-whisparr-config.yaml
  - PersistentVolumeClaim-transmission-config.yaml
  - Deployment-bazarr.yaml
  - Deployment-radarr.yaml
  - Deployment-prowlarr.yaml
  - Deployment-readarr.yaml
  - Deployment-sonarr.yaml
  - Deployment-whisparr.yaml
  - Deployment-transmission.yaml
  - Service-bazarr.yaml
  - Service-radarr.yaml
  - Service-prowlarr.yaml
  - Service-readarr.yaml
  - Service-sonarr.yaml
  - Service-whisparr.yaml
  - Service-transmission.yaml
  - Service-transmission-torrent.yaml
  - VMServiceScrape-prowlarr.yaml
  - VMServiceScrape-radarr.yaml
  - VMServiceScrape-readarr.yaml
  - VMServiceScrape-sonarr.yaml
  - VMServiceScrape-whisparr.yaml
  - VMServiceScrape-transmission.yaml

configMapGenerator:
  - name: bazarr-config-template
    options:
      disableNameSuffixHash: true
    files:
      - config/bazarr/config.yaml
  - name: transmission-config-template
    options:
      disableNameSuffixHash: true
    files:
      - config/transmission/settings.json

images:
  - name: busybox
    newName: busybox
    newTag: 1.37.0
  - name: exportarr
    newName: ghcr.io/onedr0p/exportarr
    newTag: v2.2.0
  - name: transmission
    newName: ghcr.io/home-operations/transmission
    newTag: 4.0.6
  - name: transmission-exporter
    newName: evanofslack/transmission-exporter
    newTag: latest
  - name: bazarr
    newName: ghcr.io/home-operations/bazarr
    newTag: 1.5.2
  - name: radarr
    newName: ghcr.io/home-operations/radarr
    newTag: 5.27.1.10122
  - name: prowlarr
    newName: ghcr.io/home-operations/prowlarr
    newTag: 2.0.1.5101
  - name: readarr
    newName: ghcr.io/home-operations/readarr
    newTag: 0.4.18.2805
  - name: sonarr
    newName: ghcr.io/home-operations/sonarr
    newTag: 4.0.15.2940@sha256:ca6c735014bdfb04ce043bf1323a068ab1d1228eea5bab8305ca0722df7baf78
  - name: whisparr
    newName: ghcr.io/home-operations/whisparr
    newTag: 2.0.0.1112

labels:
  - pairs:
      app.kubernetes.io/part-of: starr
