apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: sonarr
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          role: "arr-stack-sonarr"
          serviceAccountRef:
            name: sonarr
            namespace: arr-stack
