apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: starr-radarr-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: starr
spec:
  selector:
    app.kubernetes.io/name: radarr
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: radarr
    protocol: TCP
    port: 7878
    targetPort: 7878
  - name: exportarr
    protocol: TCP
    port: 9707
    targetPort: 9707
