apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: starr-prowlarr-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: starr
spec:
  selector:
    app.kubernetes.io/instance: starr-prowlarr-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: prowlarr
    protocol: TCP
    port: 9696
    targetPort: 9696
  - name: exportarr
    protocol: TCP
    port: 9707
    targetPort: 9707
