apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/part-of: starr
    app.kubernetes.io/component: app
spec:
  selector:
    app: transmission
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
  - name: metrics
    protocol: TCP
    port: 19091
    targetPort: 19091
