apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: starr-sonarr-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: starr
spec:
  selector:
    app.kubernetes.io/name: sonarr
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: sonarr
    protocol: TCP
    port: 8989
    targetPort: 8989
  - name: exportarr
    protocol: TCP
    port: 9707
    targetPort: 9707
