apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: starr-bazarr-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: starr
spec:
  selector:
    app.kubernetes.io/name: bazarr
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 6767
    targetPort: 6767
