apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  endpoints:
  - port: exportarr
    interval: 4m
    scrapeTimeout: 90s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
    - action: replace
      sourceLabels: [__name__]
      targetLabel: job
      regex: (.*)
      replacement: radarr_${1}
  namespaceSelector:
    matchNames:
    - arr-stack
