apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: prowlarr
  namespace: arr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  endpoints:
  - port: exportarr
    interval: 4m
    scrapeTimeout: 90s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelConfigs:
    - action: replace
      sourceLabels: [__name__]
      targetLabel: job
      regex: (.*)
      replacement: prowlarr_${1}
  namespaceSelector:
    matchNames:
    - arr-stack
