
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - ./manifests/namespace.yaml
  - ./manifests/pvc.yaml
  - ./manifests/deployment.yaml
  - ./manifests/service.yaml
  - ./manifests/ingress.yaml
  - ./manifests/exporter.deployment.yaml
  - ./manifests/exporter.service.yaml
  - ./manifests/service-monitor.yaml

secretGenerator:
  - name: password
    namespace: pihole
    type: Opaque
    envs:
      - .env
