apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "github-receiver-token"
spec:
  secretStoreRef:
    name: flux-system
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: github-receiver-token
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      type: Opaque

      data:
        token: "{{ .token }}"

  data:
    - secretKey: token
      remoteRef:
        key: github/receiver_token
        property: token
        decodingStrategy: None
