---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - SecretStore-flux-system.yaml
  - ExternalSecret-github-deploy-key.yaml
  - Receiver-github.yaml
  - Ingress-receiver.yaml
