apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: flux-system
  namespace: flux-system
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          role: "flux-system-notification-controller"
          serviceAccountRef:
            name: notification-controller
            namespace: flux-system
