---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
  - Namespace-operators.yaml
  - ServiceAccount-traefik.yaml
  - PersistentVolumeClaim-plugins.yaml
  - Certificate-traefik.yaml
  - HelmRelease-traefik.yaml
