
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr

commonLabels:
  app.kubernetes.io/name: radarr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: radarr
  app.kubernetes.io/component: radarr

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: radarr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
  - name: radarr-exportarr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PORT=9707
      - URL=http://radarr:7878
      - CONFIG=/config/config.xml
      - DISABLE_SSL_VERIFY=true

images:
  - name: radarr
    newName: ghcr.io/hotio/radarr
    newTag: release
  - name: exportarr
    newName: ghcr.io/onedr0p/exportarr
    newTag: v2.2.0
