---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-ddns
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/cloudflare-ddns
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: operator-external-secrets
    - name: vault
