apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kyverno-policies
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: operator-kyverno
  components:
    - ./ingress-host-match-tls.yaml
    - ./add-ingress-annotations.yaml
