---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - api-service.service-monitor.yaml
  - core-dns.service-monitor.yaml
  - kube-controller-manager.service-monitor.yaml
  - kube-scheduler.service-monitor.yaml
  - kubelet.service-monitor.yaml
  - prometheus-rule.yaml
