---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lldap

resources:
  - ./manifests/namespace.yaml
  - ./manifests/service.yaml
  - ./manifests/db.yaml
  - ./manifests/deployment.yaml
  - ./manifests/ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: lldap-credentials
    type: Opaque
    env: secret.env
  - name: lldap-db-creds
    type: Opaque
    literals:
      - username=lldap
      - password=lldap
  - name: superuser-secret
    type: Opaque
    literals:
      - username=postgres
      - password=postgres

configMapGenerator:
  - name: lldap-config
    env: config.env
