apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-canary
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki-canary
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-canary
  endpoints:
  - port: http-metrics
