apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: operators
spec:
  interval: 10m
  ref:
    tag: v0.18.2
  url: http://github.com/external-secrets/external-secrets
