apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: operators
spec:
  interval: 10m
  path: ./deploy/crds
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: external-secrets
    namespace: operators
