---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
  - Namespace-operators.yaml
  - GitRepository-external-secrets.yaml
  - Kustomization-external-secrets-crds.yaml
  - HelmRelease-external-secrets.yaml
