---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-ddns

commonLabels:
  app.kubernetes.io/name: cloudflare-ddns
  app.kubernetes.io/instance: cloudflare-ddns
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: cloudflare-ddns
  app.kubernetes.io/version: v1.0.0

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml


secretGenerator:
  - name: cloudflare-ddns-config
    type: Opaque
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: cloudflare-ddns
        app.kubernetes.io/instance: cloudflare-ddns
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/component: cloudflare-ddns
        app.kubernetes.io/version: v1.0.0
    files:
      - config.json
