---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/namespace.yaml
  - ./manifests/deployment.yaml

namespace: cloudflare-ddns

secretGenerator:
  - name: config
    type: Opaque
    files:
      - ./config/config.json
