apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# Flux OpenTofu controller
- flux-opentofu-controller.yaml
- receiver.yaml
- webhook-ingress.yaml
