apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# Flux OpenTofu controller
- https://raw.githubusercontent.com/flux-iac/tofu-controller/refs/tags/v0.15.1/docs/release.yaml
- receiver.yaml
- webhook-ingress.yaml
- helm-repositories
