apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/namespace.yaml
- manifests/redis.yaml
- manifests/persistent-volume-claim.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml

commonLabels:
  app.kubernetes.io/name: registry
  app.kubernetes.io/instance: registry
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: registry
  app.kubernetes.io/part-of: slfhst
  app.kubernetes.io/version: 2.8.3

namespace: registry

images:
- name: registry
  newName: registry
  newTag: 2.8.3

configMapGenerator:
- name: config
  options:
    disableNameSuffixHash: true
  literals:
    - REGISTRY_LOG_LEVEL=debug
    - REGISTRY_HTTP_ADDR=registry.slfhst.io
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/tls.crt
    - REGISTRY_HTTP_TLS_KEY=/certs/tls.key
    - REGISTRY_HTTP_TLS_ROOTCAS=/certs/ca.crt
    - REGISTRY_AUTH_TOKEN_REALM=https://login.slfhst.io/realms/master/protocol/docker-v2/auth
    - REGISTRY_AUTH_TOKEN_SERVICE=docker-registry
    - REGISTRY_AUTH_TOKEN_ISSUER=https://login.slfhst.io/realms/master
