apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/part-of: slfhst
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: 22.0.5

resources:
  - manifests/namespace.yaml
  - manifests/database.cluster.yaml
  - manifests/service.yaml
  - manifests/certificate.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml


secretGenerator:
  - name: keycloak-admin-user
    env: .env


images:
  - name: keycloak
    newName: sbordeyne/keycloak
    newTag: 23.0.0
