apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanidm-tls
  namespace: kanidm
spec:
  dnsNames:
  - auth.slfhst.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: kanidm-tls
  usages:
  - digital signature
  - key encipherment
