apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: default
  labels:
    app: lldap
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
