apiVersion: v1
kind: Service
metadata:
  labels:
    app: lldap
  name: lldap
  namespace: lldap
spec:
  ports:
    - name: "http"
      port: 17170
      targetPort: 17170
    - name: "ldap"
      port: 3890
      targetPort: 3890
    - name: "ldaps"
      port: 6360
      targetPort: 6360
  type: ClusterIP

  selector:
    app: lldap
