kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acme-storage-claim
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
