apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-cache-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 10Gi
