kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      namespace: traefik
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      volumes:
        - name: acme-storage-volume
          persistentVolumeClaim:
            claimName: acme-storage-claim
        - name: traefik-config
          configMap:
            name: traefik-config
        - name: simple-cache
          persistentVolumeClaim:
            claimName: simple-cache-claim
      containers:
        - name: traefik
          image: traefik:v2.10
          envFrom:
            - secretRef:
                name: traefik-secrets
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
            - name: metrics
              containerPort: 8082
          volumeMounts:
            - name: acme-storage-volume
              mountPath: /acme
              subPath: ""
            - name: simple-cache
              mountPath: /simple-cache
            - name: traefik-config
              mountPath: /etc/traefik/traefik.toml
              subPath: traefik.toml
