apiVersion: apps/v1
kind: Deployment
metadata:
  name:  paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name:  paperless-ngx
        image:  ghcr.io/paperless-ngx/paperless-ngx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: paperless-ngx-env
          - secretRef:
              name: paperless-ngx-secret
        ports:
        - containerPort:  80
          name:  paperless-ngx
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: 
      restartPolicy: Always
