---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: monitoring

secretGenerator:
  - name: grafana-config
    namespace: monitoring
    type: Opaque
    options:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
    files:
      - grafana.ini
  - name: grafana-env
    namespace: monitoring
    type: Opaque
    options:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
    env: .env
