---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
  - Namespace-operators.yaml
  - HelmRelease-vm-operator-crds.yaml
  - HelmRelease-vm-operator.yaml
