---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/namespace.yaml
  - ./manifests/cluster-issuer.yaml

namespace: cert-manager

secretGenerator:
  - name: cloudflare-api-key
    type: Opaque
    namespace: cert-manager
    env: .env
