apiVersion: v1
kind: Service
metadata:
  name: smart-exporter
  namespace: monitoring
spec:
  selector:
    app: smart-exporter
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 9120
    targetPort: 9120
