
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openldap

resources:
  - ./manifests/namespace.yaml
  - ./manifests/pvc.yaml
  - ./manifests/service.yaml
  - ./manifests/deployment.yaml

commonLabels:
  app.kubernetes.io/name: openldap
  app.kubernetes.io/instance: openldap
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: openldap
  app.kubernetes.io/part-of: openldap
  app.kubernetes.io/version: 2.6.6

configMapGenerator:
  - name: openldap-env
    literals:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ROOT=dc=slfhst,dc=io
      - LDAP_ADMIN_DN=cn=admin,dc=slfhst,dc=io
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap-admin-password
      # - LDAP_CUSTOM_LDIF_DIR=/ldif
      - LDAP_CONFIGURE_PPOLICY=yes
      - LDAP_PPOLICY_USE_LOCKOUT=yes
      - LDAP_PPOLICY_HASH_CLEARTEXT=yes

secretGenerator:
  - name: openldap-admin-password
    files:
      - ldap-admin-password
    type: Opaque

images:
  - name: openldap
    newName: bitnami/openldap
    newTag: 2.6.6
