apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radarr-monitor
  namespace: arr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  endpoints:
  - port: exportarr
    interval: 4m
    scrapeTimeout: 90s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
    - action: replace
      sourceLabels: [__name__]
      targetLabel: job
      regex: (.*)
      replacement: radarr_${1}
  namespaceSelector:
    matchNames:
    - arr
