---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases-postgresql
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/databases/postgresql
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
