
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr

commonLabels:
  app.kubernetes.io/name: sonarr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: sonarr
  app.kubernetes.io/component: sonarr

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: sonarr-env
    namespace: sonarr
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: sonarr
        app.kubernetes.io/part-of: arrstack
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/component: sonarr
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
  - name: sonarr-exportarr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PORT=9707
      - URL=http://sonarr:8989
      - CONFIG=/config/config.xml
      - DISABLE_SSL_VERIFY=true

images:
  - name: sonarr
    newName: hotio/sonarr
    newTag: release
  - name: exportarr
    newName: ghcr.io/onedr0p/exportarr
    newTag: v2.2.0
