apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sonarroidc
  namespace: traefik
spec:
  plugin:
    keycloakopenid:
      ClientIDEnv: KEYCLOAK_SONARR_CLIENT_ID
      ClientSecretEnv: KEYCLOAK_SONARR_CLIENT_SECRET
      KeycloakRealm: master
      KeycloakURL: https://login.slfhst.io
      Scope: openid profile email
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "true"
      UserClaimName: "preferred_username"
      UserHeaderName: "X-Forwarded-User"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: bazarroidc
  namespace: traefik
spec:
  plugin:
    keycloakopenid:
      ClientIDEnv: KEYCLOAK_BAZARR_CLIENT_ID
      ClientSecretEnv: KEYCLOAK_BAZARR_CLIENT_SECRET
      KeycloakRealm: master
      KeycloakURL: https://login.slfhst.io
      Scope: openid profile email
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "true"
      UserClaimName: "preferred_username"
      UserHeaderName: "X-Forwarded-User"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prowlarroidc
  namespace: traefik
spec:
  plugin:
    keycloakopenid:
      ClientIDEnv: KEYCLOAK_PROWLARR_CLIENT_ID
      ClientSecretEnv: KEYCLOAK_PROWLARR_CLIENT_SECRET
      KeycloakRealm: master
      KeycloakURL: https://login.slfhst.io
      Scope: openid profile email
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "true"
      UserClaimName: "preferred_username"
      UserHeaderName: "X-Forwarded-User"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: radarroidc
  namespace: traefik
spec:
  plugin:
    keycloakopenid:
      ClientIDEnv: KEYCLOAK_RADARR_CLIENT_ID
      ClientSecretEnv: KEYCLOAK_RADARR_CLIENT_SECRET
      KeycloakRealm: master
      KeycloakURL: https://login.slfhst.io
      Scope: openid profile email
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "true"
      UserClaimName: "preferred_username"
      UserHeaderName: "X-Forwarded-User"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whisparroidc
  namespace: traefik
spec:
  plugin:
    keycloakopenid:
      ClientIDEnv: KEYCLOAK_WHISPARR_CLIENT_ID
      ClientSecretEnv: KEYCLOAK_WHISPARR_CLIENT_SECRET
      KeycloakRealm: master
      KeycloakURL: https://login.slfhst.io
      Scope: openid profile email
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "true"
      UserClaimName: "preferred_username"
      UserHeaderName: "X-Forwarded-User"
