
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr

commonLabels:
  app.kubernetes.io/name: prowlarr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: prowlarr
  app.kubernetes.io/component: prowlarr

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: prowlarr-env
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/part-of: arrstack
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/component: prowlarr
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
  - name: prowlarr-exportarr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PORT=9707
      - URL=http://prowlarr:9696
      - CONFIG=/config/config.xml
      - DISABLE_SSL_VERIFY=true
      - PROWLARR__BACKFILL=true

images:
  - name: prowlarr
    newName: hotio/prowlarr
    newTag: release
  - name: exportarr
    newName: ghcr.io/onedr0p/exportarr
    newTag: v1.5.3
