apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/component: ntfy-monitor
    app.kubernetes.io/instance: ntfy-monitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ntfy-monitor
    app.kubernetes.io/part-of: ntfy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - ntfy
