---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-storage-provisioner
  namespace: operators
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-storage-provisioner
        namespace: flux-system
  values:
    nfs:
      server: 192.168.1.42
      path: /tank/persistentvolumes
    storageClass:
      name: nfs-client
      defaultClass: true
      reclaimPolicy: Retain
      onDelete: delete
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
