apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gotenberg
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gotenberg
      app.kubernetes.io/part-of: paperless-ngx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name:  gotenberg
        image:  gotenberg
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort:  3000
          name:  gotenberg
        args: ["--chromium-disable-javascript=true", "--chromium-allow-list=file:///tmp/.*"]
        command: ['gotenberg']
      restartPolicy: Always
