---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: gotenberg
    newName: docker.io/gotenberg/gotenberg
    newTag: '7.10'

namespace: paperless-ngx

commonLabels:
  app.kubernetes.io/name: gotenberg
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: gotenberg
  app.kubernetes.io/part-of: paperless-ngx
