apiVersion: v1
kind: Service
metadata:
  name: gotenberg
spec:
  selector:
    app.kubernetes.io/name: gotenberg
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: gotenberg
    protocol: TCP
    port: 3000
    targetPort: 3000

