apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  openldap
    spec:
      containers:
      - name:  openldap
        image:  openldap
        securityContext:
          allowPrivilegeEscalation: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: BITNAMI_DEBUG
            value: "true"
        envFrom:
          - configMapRef:
              name:  config
          - secretRef:
              name: openldap-secrets
        ports:
        - containerPort:  1339
          name:  openldap
        - containerPort:  1636
          name:  openldaps
        volumeMounts:
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.ca.crt
          subPath: ca.crt
          readOnly: true
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.crt
          subPath: tls.crt
          readOnly: true
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.key
          subPath: tls.key
          readOnly: true
        - name: data
          mountPath: /bitnami
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      volumes:
        - name: tls
          secret:
            secretName: openldap-tls
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc
      restartPolicy: Always
