apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml

namespace: arr

commonLabels:
  app.kubernetes.io/name: whisparr
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: whisparr
  app.kubernetes.io/component: whisparr

configMapGenerator:
  - name: whisparr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
  - name: whisparr-exportarr-env
    options:
      disableNameSuffixHash: true
    literals:
      - PORT=9707
      - URL=http://whisparr:6969
      - CONFIG=/config/config.xml
      - DISABLE_SSL_VERIFY=true

images:
  - name: whisparr
    newName: ghcr.io/hotio/whisparr
    newTag: latest
  - name: exportarr
    newName: ghcr.io/onedr0p/exportarr
    newTag: v1.6.2
