#!/usr/bin/env bash

# Install Dasel (for config edits)
curl -LO https://github.com/TomWright/dasel/releases/download/v2.3.6/dasel_linux_amd64
sudo mv dasel_linux_amd64 /usr/local/bin/dasel
sudo chmod +x /usr/local/bin/dasel

# Disable swap (unsupported by Kubernetes)
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# Remove old Kubernetes config
sudo rm -rf $HOME/.kube/config
sudo rm -rf $HOME/.kube/cache

# Install firewall, update rules
sudo apt-get install ufw -y
sudo ufw enable
sudo ufw allow 6443/tcp
sudo ufw allow 2379/tcp
sudo ufw allow 2380/tcp
sudo ufw allow 10250/tcp
sudo ufw allow 10251/tcp
sudo ufw allow 10252/tcp
sudo ufw allow 10255/tcp
sudo ufw reload

# Install containerd
cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF
sudo modprobe overlay
sudo modprobe br_netfilter
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-k8s.conf
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF
sudo sysctl --system
sudo apt update && sudo apt install -y containerd
containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
# Need to edit the config SystemdCGroup = true
sudo systemctl restart containerd
sudo systemctl enable containerd

sudo apt install gnupg gnupg2 curl software-properties-common -y
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/cgoogle.gpg
sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

sudo apt-get update
sudo apt-get install kubelet kubeadm kubectl -y
sudo apt-mark hold kubelet kubeadm kubectl

sudo kubeadm init --control-plane-endpoint nas-master
sudo mkdir -p $HOME/.kube
sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

sudo kubeadm init phase certs all --config ./kubeadm.yaml

kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
kubectl taint node nas-master.local node-role.kubernetes.io/control-plane-
kubectl config rename-context kubernetes-admin@kubernetes main
