apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
      #    service-node-port-range: 0-32767
  timeoutForControlPlane: 4m0s
  certSANs:
  - "nas.dogeek.me"
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: nas-master:6443
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.28.2
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
