#!/usr/bin/env python3

from pathlib import Path
import json


ROOT = Path(__file__).parent
INGRESS_TPL = """
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {app_name}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {app_name}.nas.dogeek.me
    external-dns.alpha.kubernetes.io/target: nas.dogeek.me
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  tls:
  - hosts:
    - {app_name}.nas.dogeek.me
    secretName: {app_name}-cert-prod
  rules:
  - host: {app_name}.nas.dogeek.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {app_name}
            port:
              name: http
"""


def bootstrap_app(app_name: str):
    # Make a directory in the tree
    # Initialize the kustomization.yaml, and namespace manifests
    (ROOT / app_name).mkdir(exist_ok=True)
    (ROOT / app_name / 'manifests').mkdir(exist_ok=True)
    (ROOT / app_name / 'manifests' / 'ingress.yaml').write_text(
        INGRESS_TPL.format(app_name=app_name)
    )

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('app_name')
    args = parser.parse_args()
    bootstrap_app(args.app_name)
