#!/usr/bin/env python3

import secrets
# Generates secrets that are gitignored from this repo

# TODO

# Borgbase
BORGBASE_API_TOKEN = input("Borgbase API Token: ")
BORGBASE_SSH_URL = input("Borgbase SSH URL: ")
BORGBASE_SSH_PRIVATE_KEY = input("Borgbase SSH Private Key: ")
BORGBASE_SSH_PUBLIC_KEY = input("Borgbase SSH Public Key: ")

# Cloudflare
CLOUDFLARE_API_TOKEN = input("Cloudflare API Token: ")
CLOUDFLARE_API_KEY = input("Cloudflare API Key: ")

# External DNS
TXT_ENCRYPT_SECRET = secrets.token_urlsafe(64)
PIHOLE_PASSWORD = secrets.token_urlsafe(64)

# SMTP Relay
SMTP_MAILJET_API_KEY = input("Mailjet API Key: ")
SMTP_MAILJET_API_SECRET = input("Mailjet API Secret: ")

TRANSMISSION_PASSWORD = secrets.token_urlsafe(64)
