apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cloudflare-ddns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-ddns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: timothyjmiller/cloudflare-ddns:latest
        name: cloudflare-ddns
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Paris"
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
      volumes:
        - name: config
          secret:
            secretName: cloudflare-ddns-config
      restartPolicy: Always
