apiVersion: apps/v1
kind: Deployment
metadata:
  name:  qbittorrent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
      - image: lscr.io/linuxserver/qbittorrent:latest
        name: qbittorrent
        resources:
          limits:
            cpu: "100m"
            memory: "256M"
          requests:
            cpu: "20m"
            memory: "55M"
        envFrom:
          - configMapRef:
              name: qbittorrent-env
              optional: false
        ports:
        - containerPort:  9696
          name:  http
        volumeMounts:
        - mountPath: /media
          name: media
        - mountPath: /config
          name: config
      volumes:
        - name: media
          nfs:
            path: /tank/media
            server: "192.168.1.42"
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
