---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
  - Namespace-operators.yaml
  - ServiceAccount-external-dns.yaml
  - ClusterRole-external-dns.yaml
  - ClusterRoleBinding-external-dns-viewer.yaml
  - SecretStore-external-dns.yaml
  - Terraform-external-dns.yaml
