apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-dns
  namespace: operators
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          role: "operators-external-dns"
          serviceAccountRef:
            name: external-dns
            namespace: operators
          secretRef:
            name: "external-dns-jwt"
            key: "token"
