apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-dns
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        kubernetes:
          role: "external-dns"
