apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-dns
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          role: "operators-external-dns"
