apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: openldap
        image: openldap
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: openldap-env
        ports:
        - containerPort:  1389
          name:  ldap
        - containerPort:  1636
          name:  ldaps
        volumeMounts:
        - name: openldap-admin-secret
          mountPath: /run/secrets/ldap-admin-password
          readOnly: true
          subPath: ldap-admin-password
      volumes:
        - name: openldap-admin-secret
          secret:
            secretName: openldap-admin-password
      restartPolicy: Always
