all:
  hosts:
    node1:
      ansible_host: 192.168.1.42
    node2:
      ansible_host: 192.168.1.14
    node3:
      ansible_host: 192.168.1.18
  children:
    kube_control_plane:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
