apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.nas.dogeek.me
    external-dns.alpha.kubernetes.io/target: nas.dogeek.me
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  tls:
  - hosts:
    - prowlarr.nas.dogeek.me
    secretName: prowlarr-cert-prod
  rules:
  - host: prowlarr.nas.dogeek.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              name: http
