apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/component: cloudflare
  template:
    metadata:
      labels:
        app: external-dns
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/component: cloudflare
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: external-dns
        args:
        - --source=ingress # ingress is also possible
        - --domain-filter=slfhst.io # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=cloudflare
        - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request
        - --txt-owner-id=external-dns
        - --registry=txt
        - --txt-prefix=k8s-nas-%{record_type}-
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
          - name:  CF_API_KEY
            valueFrom:
              secretKeyRef:
                name:  api-key
                key:  CLOUDFLARE_API_KEY
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                name:  api-key
                key:  CLOUDFLARE_API_EMAIL
          - name: TXT_ENCRYPT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-key
                key: TXT_ENCRYPT_SECRET
