apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "external-dns-cloudflare"
spec:
  secretStoreRef:
    name: external-dns
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: "1h"

  target:
    name: external-dns-cloudflare-api-key
    creationPolicy: Owner
    deletionPolicy: Delete

    # Specify a blueprint for the resulting Kind=Secret
    template:
      type: Opaque

      # Use inline templates to construct your desired config file that contains your secret
      data:
        CLOUDFLARE_API_KEY: {{ .key }}
        CLOUDFLARE_API_EMAIL: {{ .email }}
        TXT_ENCRYPT_SECRET: {{ .txtEncrypt }}

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: key
      remoteRef:
        key: cloudflare/credentials
        version: latest
        property: api_key
        decodingStrategy: None
    - secretKey: email
      remoteRef:
        key: cloudflare/credentials
        version: latest
        property: email
        decodingStrategy: None
    - secretKey: txtEncrypt
      remoteRef:
        key: external-dns/txt-encrypt
        version: latest
        property: key
        decodingStrategy: None
