
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr

commonLabels:
  app.kubernetes.io/name: transmission
  app.kubernetes.io/part-of: arrstack
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: transmission
  app.kubernetes.io/component: transmission

resources:
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  # - manifests/ingress.yaml
  - manifests/service-monitor.yaml

configMapGenerator:
  - name: transmission-env
    namespace: transmission
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: transmission
        app.kubernetes.io/part-of: transmission
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/component: transmission
    literals:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - PEERPORT=51413

  - name: transmission-settings
    namespace: transmission
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: transmission
        app.kubernetes.io/part-of: transmission
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/component: transmission
    files:
      - config/settings.json

secretGenerator:
  - name: transmission
    namespace: transmission
    type: kubernetes.io/basic-auth
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: transmission
        app.kubernetes.io/part-of: transmission
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/component: transmission
    env: .env

images:
  - name: transmission
    newName: jaymoulin/transmission
    newTag: latest
  - name: transmission-exporter
    newName: evanofslack/transmission-exporter
    newTag: latest
