apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tika
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tika
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  tika
    spec:
      containers:
      - name:  tika
        image:  tika
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 50m
            memory: 300Mi
        ports:
        - containerPort:  9998
          name:  tika
      restartPolicy: Always
