---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: paperless-ngx

commonLabels:
  app.kubernetes.io/name: tika
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: tika
  app.kubernetes.io/part-of: paperless-ngx

images:
  - name: tika
    newName: ghcr.io/paperless-ngx/tika
    newTag: latest
