apiVersion: v1
kind: Service
metadata:
  name: tika
spec:
  selector:
    app.kubernetes.io/name: tika
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: tika
    protocol: TCP
    port: 9998
    targetPort: 9998
