apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      namespace: kube-system
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        args:
        - --source=ingress
        - --provider=pihole
        - --registry=noop
        - --policy=upsert-only
        - --pihole-server=http://pihole.pihole.svc.cluster.local:80
        - --pihole-tls-skip-verify=true
        securityContext:
          fsGroup: 65534
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
          - name:  CF_API_KEY
            valueFrom:
              secretKeyRef:
                name:  api-key
                key:  CLOUDFLARE_API_KEY
          - name: CF_API_EMAIL
            value: "simon.bordeyne@gmail.com"
          - name: TXT_ENCRYPT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-key
                key: TXT_ENCRYPT_SECRET
