---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress-route.yaml

namespace: warsow-server

commonLabels:
  app.kubernetes.io/name: warsow-server
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: warsow-config
    options:
      disableNameSuffixHash: true
    files:
      - config/dedicated_autoexec.cfg
