---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/namespace.yaml
  - ./manifests/service-account.yaml
  - ./manifests/role.yaml
  - ./manifests/role-binding.yaml
  - ./manifests/service.yaml
  - ./manifests/deployment.yaml
  # - ./components/tester.cronjob.yaml

namespace: smtp-relay

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: smtp-relay
  app.kubernetes.io/part-of: smtp-relay
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: smtp-relay
  app.kubernetes.io/component: smtp-relay
  app.kubernetes.io/version: "0.6.1"

configMapGenerator:
  - name: smtp-relay-env
    namespace: smtp-relay
    literals:
      - SMTP_SERVER_HOSTNAME=0.0.0.0
      - SMTP_SERVER_PORT=8025
      - LOG_LEVEL=info
      - SMTP_SERVICE=mailjet

secretGenerator:
  - name: smtp-relay-secret
    type: Opaque
    namespace: smtp-relay
    env: .env
