---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/service-account.yaml
  - manifests/role.yaml
  - manifests/role-binding.yaml
  - manifests/service.yaml
  - manifests/deployment.yaml

namespace: smtp-relay

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: smtp-relay
  app.kubernetes.io/managed-by: kustomize

secretGenerator:
  - name: smtp-relay-env
    type: Opaque
    namespace: smtp-relay
    env: .env
