---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: paperless-ngx
  app.kubernetes.io/instance: paperless-ngx
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: paperless-ngx

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: paperless-ngx-env
    literals:
      - USERMAP_UID=1000
      - USERMAP_GID=1000
      # - PAPERLESS_OCR_LANGUAGES=eng
      - PAPERLESS_URL=https://docs.slfhst.io
      - PAPERLESS_TIME_ZONE=Europe/Paris
      # - PAPERLESS_OCR_LANGUAGE=fra
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=postgresql
      - PAPERLESS_TIKA_ENABLED=true
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_CONSUMPTION_DIR=/paths/consume
      - PAPERLESS_DATA_DIR=/paths/data
      - PAPERLESS_TRASH_DIR=/paths/trash
      - PAPERLESS_MEDIA_ROOT=/paths/media
      - PAPERLESS_FILENAME_FORMAT={owner_username}/{correspondent}/{created}-{doc_pk}-{title}
      - PAPERLESS_APPS="allauth.socialaccount.providers.openid_connect"
      - PAPERLESS_SOCIAL_AUTO_SIGNUP=true
      - PAPERLESS_DISABLE_REGULAR_LOGIN=true


secretGenerator:
  - name: paperless-ngx-secret
    type: Opaque
    env: .env

images:
  - name: paperless-ngx
    newName: ghcr.io/paperless-ngx/paperless-ngx
    newTag: latest
