---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/operators/cert-manager
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
