---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/operators/external-secrets
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
