---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/operators/external-dns
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: operator-external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
