---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-nfs-storage-provisioner
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/operators/nfs-storage-provisioner
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
