---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator-traefik
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/operators/traefik
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: operator-cert-manager-issuers
    - name: operator-victoriametrics
  sourceRef:
    kind: GitRepository
    name: flux-system
