apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: warsow-server-ingress-udp
  namespace: warsow-server
  labels:
    app.kubernetes.io/name: warsow-server
spec:
  entryPoints:
    - warsow
  routes:
  - services:
    - name: warsow-server-udp
      port: 44400
      nativeLB: true
      weight: 10

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: warsow-server-ingress-tcp
  namespace: warsow-server
  labels:
    app.kubernetes.io/name: warsow-server
spec:
  entryPoints:
    - web
  routes:
  - match: HostSNI(`wsw.slfhst.io`)
    services:
    - name: warsow-server
      port: 44444
