---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 5m
  upgrade:
    remediation:
      retries: 3
    timeout: 5m
  values:
    server:
      service:
        type: NodePort
        nodePort: 8200
