---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - Namespace-vault.yaml
  - ServiceAccount-vault-auth.yaml
  - ClusterRoleBinding-vault-auth-delegator.yaml
  - HelmRelease-vault.yaml
