
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - manifests/namespace.yaml
  - manifests/pvc.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/deployment.yaml
  - manifests/service-monitor.yaml

images:
  - name: jellyfin
    newName: jellyfin/jellyfin
    newTag: 10.8.13-1
