name: ansible-lint
on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.5.0
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: "ansible"
          requirements_file: "ansible/requirements.yaml"
