name: Lint Ansible files

permissions:
  contents: read # to fetch the repository content

on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ansible-lint
        uses: ansible/ansible-lint@06f616d6e86e9ce4c74393318d1cbb2d016af413 # v25.6.1
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: "ansible"
          requirements_file: "ansible/requirements.yaml"
