name: Build Docker Images

on:
  push:
    paths:
      - '.github/workflows/build-docker-images.yaml'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: tf-runner
            build_args: |-
              TARGETARCH=amd64
              TF_VERSION=1.11.4
              TF_CONTROLLER_VERSION=v0.16.0-rc.5
            tag: "1.11.4"
          - name: keycloak
            build_args: |-
              KC_VERSION=22.0.5
            tag: "22.0.5"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          build_args=""
          while IFS= read -r line; do
            build_args="$build_args --build-arg $line"
          done <<< "${{ matrix.build_args }}"
          echo "Building Docker image with args: $build_args"
          docker build \
            $build_args \
            -t ${{ matrix.name }}:${{ matrix.tag }} \
            --label "org.opencontainers.image.source=https://github.com/sbordeyne/selfhosted" \
            ./docker/${{ matrix.name }}

      - name: Push Docker image to ghcr.io
        run: |
          echo "Pushing Docker image ${{ matrix.name }}:${{ matrix.tag }}"
          docker tag ${{ matrix.name }}:${{ matrix.tag }} ghcr.io/${{github.actor}}/${{ matrix.name }}:${{ matrix.tag }}
          docker push ghcr.io/${{github.actor}}/${{ matrix.name }}:${{ matrix.tag }}
