name: Check app file names

permissions:
  contents: read # to fetch the repository content

on:
  push:
    branches:
      - master
    paths:
      - "apps/**/*"
  pull_request:

jobs:
  check-file-names:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up yq
        uses: mikefarah/yq@1187c954ec44c3a0e62c13ca7dc9dadc1ca80ae7 # v4.46.1
        with:
          version: 'v4.34.1'

      - name: Check file names
        run: bash scripts/check-file-names.sh
