name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  components:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
          - kubernetes
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Check for updates
        id: update
        run: |
          flux install \
            --components-extra=image-reflector-controller,image-automation-controller \
            --export > ./clusters/${{matrix.cluster}}/flux-system/gotk-components.yaml
          VERSION="$(flux -v)"
          echo "flux_version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
            branch: update-flux-${{matrix.cluster}}
            commit-message: Update ${{matrix.cluster}} to ${{ steps.update.outputs.flux_version }}
            title: Update ${{matrix.cluster}} to ${{ steps.update.outputs.flux_version }}
            body: ""
