apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: polygone

spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  storage:
    size: 10Gi
    storageClass: nfs-client
