apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak

spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-creds

  storage:
    storageClass: nfs-client
    size: 1Gi
