apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
        - name: keycloak-certs
          secret:
            secretName: keycloak-cert-prod
      containers:
        - name: keycloak
          resources:
            limits:
              memory: '512Mi'
              cpu: '100m'
            requests:
              memory: '256Mi'
              cpu: '50m'
          image: sbordeyne/keycloak:latest
          imagePullPolicy: Always
          args: [
            "--config-file=/config/keycloak.conf",
            "start",
            "--optimized",
          ]
          envFrom:
            - secretRef:
                name: keycloak-credentials
            - configMapRef:
                name: keycloak-env
          volumeMounts:
            - name: keycloak-config
              mountPath: /config/keycloak.conf
              subPath: keycloak.conf
              readOnly: true
            - name: keycloak-certs
              mountPath: /certs
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
