apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - keycloak
