apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: komga

resources:
- pvc.yaml
- api.deployment.yaml
- api.service.yaml
- api.ingress.yaml
- front.deployment.yaml
- front.service.yaml
- front.ingress.yaml

commonLabels:
  app.kubernetes.io/name: tranga
  app.kubernetes.io/version: latest
  app.kubernetes.io/instance: tranga
  app.kubernetes.io/part-of: komga
  app.kubernetes.io/managed-by: kustomize

images:
- name: tranga-api
  newName: glax/tranga-api
  newTag: latest
- name: tranga-front
  newName: glax/tranga-website
  newTag: latest
