apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flaresolverr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  flaresolverr
    spec:
      hostNetwork: false
      hostPID: false
      shareProcessNamespace: false
      enableServiceLinks: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 8Gi
        envFrom:
          - configMapRef:
              name: flaresolverr-env
              optional: false
        env:
        - name: TZ
          value: Europe/Paris
        ports:
        - containerPort:  8191
          name:  http
