apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
          - configMapRef:
              name: flaresolverr-env
              optional: false
        env:
        - name: TZ
          value: Europe/Paris
        ports:
        - containerPort:  8191
          name:  http
      restartPolicy: Always
