apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8191
    targetPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-metrics
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: metrics
    protocol: TCP
    port: 8192
    targetPort: 8192
